name: CI and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci || npm install

      - name: Lint
        run: npm run -s lint || echo "Lint step skipped"

      - name: Build
        run: npm run -s build

      - name: Upload build artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            .next
            next.config.js
            next.config.mjs
            package.json
            package-lock.json
            public
          if-no-files-found: warn

  deploy_pages:
    name: Deploy to GitHub Pages (if static export)
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build and Export static site
        run: |
          npm run -s build
          npx --yes next export -o out || echo "Static export failed; skipping Pages deploy"

      - name: Configure Pages
        if: hashFiles('out/**') != ''
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        if: hashFiles('out/**') != ''
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

      - name: Deploy to GitHub Pages
        if: hashFiles('out/**') != ''
        id: deployment
        uses: actions/deploy-pages@v4
